services:

  hz:
    image: hazelcast/hazelcast:latest
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
      CLASSPATH: /project/common/target/common-1.0-SNAPSHOT.jar
    volumes:
      - ".:/project"
    networks:
      - hznet
    ports:
      - "5701:5701"

  mc:
    image: hazelcast/management-center:latest
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz
    ports:
      - "8080:8080"
    networks:
      - hznet

  submit_job:
    image: hazelcast/hazelcast:latest
    volumes:
      - ".:/project"
    command: /project/cli/submitjob.sh
    networks:
    - hznet
    profiles:
      - disabled

  cancel_job:
    image: hazelcast/hazelcast:latest
    volumes:
      - ".:/project"
    command: /project/cli/canceljob.sh
    networks:
      - hznet
    profiles:
      - disabled

  refdata_loader:
    image: openjdk:11
    command: java -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev
      MACHINE_COUNT: 10
      SIMULATOR_CONFIG_FILE: /project/config/machine_profiles_small.csv
    volumes:
      - ".:/project"
    networks:
      - hznet

  event_generator:
    image: openjdk:11
    command: java -jar /project/event-generator/target/event-generator-1.0-SNAPSHOT.jar
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev 
      MACHINE_COUNT: 10
    volumes:
      - ".:/project"
    networks:
      - hznet
  
  ui:
    build:
      context: ./ui
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev
    ports:
      - "8050:8050"
    networks:
      - hznet


networks:
  hznet: 
  
