services:

  refdata_loader:
    image: openjdk:11
    command: java -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
    environment:
      MACHINE_COUNT: 1000
      SIMULATOR_CONFIG_FILE: /project/config/machine_profiles_medium.csv
      VIRIDIAN_SECRETS_DIR: /viridianconfig
    volumes:
      - ".:/project"
      - "${VIRIDIAN_SECRETS_DIR}:/viridianconfig"
    networks:
      - hznet

  event_generator:
    image: openjdk:11
    command: java -jar /project/event-generator/target/event-generator-1.0-SNAPSHOT.jar
    environment:
      MACHINE_COUNT: 1000
      VIRIDIAN_SECRETS_DIR: /viridianconfig
    volumes:
      - ".:/project"
      - "${VIRIDIAN_SECRETS_DIR}:/viridianconfig"
    networks:
      - hznet
  
  ui:
    build:
      context: ./ui
    ports:
      - "8050:8050"
    environment:
      VIRIDIAN_SECRETS_DIR: /viridianconfig
    volumes:
      - ".:/project"
      - "${VIRIDIAN_SECRETS_DIR}:/viridianconfig"
    networks:
      - hznet

networks:
  hznet: 
  
