services:

  refdata_loader:
    image: openjdk:11
    command: java -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
    env_file:
      - viridian.env
    environment:
      MACHINE_COUNT: 1000
      SIMULATOR_CONFIG_FILE: /project/config/machine_profiles_medium.csv
    volumes:
      - ".:/project"
    networks:
      - hznet

  event_generator:
    image: openjdk:11
    command: java -jar /project/event-generator/target/event-generator-1.0-SNAPSHOT.jar
    env_file:
      - viridian.env
    environment:
      MACHINE_COUNT: 1000
    volumes:
      - ".:/project"
    networks:
      - hznet
  
  ui:
    build:
      context: ./ui
    env_file:
      - viridian.env
    ports:
      - "8050:8050"
    volumes:
      - ".:/project"
    networks:
      - hznet

networks:
  hznet: 
  
